### ISSUE TITLE
Failed to resolve scalar expression named IpAddress for AzureHoundActivityDetected.yaml

### ISSUE THREAD

**Issue by c3rberus** [f-bader/AzSentinelQueries#1]
Hello,

Trying to import the NRT rules to for Sentinel Analytics (from https://cloudbrothers.info/en/detect-threats-microsoft-graph-logs-part-1), the error I get is below...

`'summarize' operator: Failed to resolve scalar expression named 'IpAddress'`

Seems to be with any of the Analytics rules on that blog post where there is reference to IpAddress.

Any ideas what is causing this?

**Comment by f-bader** [comment]
Yes, there was an announced change that the field will be renamed to `IPAddress`

Seems this is now the case and I have to update the detection file. You can manually search and replace for it in the file

**Comment by f-bader** [comment]
Updated yaml files in #2

**Comment by c3rberus** [comment]
Thanks, I was staring at the field and didn't realize it was case sensetive!
