### ISSUE TITLE
anonymous icloud ip auto close question

### ISSUE THREAD

**Issue by d3f3nder** [f-bader/AzSentinelQueries#4]
Hi, first i'd like to say thanks for this playbook, secondly, how in the world do i get this up and running? 

I am trying to find some good instructions on how to use the code and template but that that was quickly becoming a rabbit hole. 

In your cloudbrothers post you mention to let you know if more info was needed on how to get this working, Well consider this a first request :)

**Comment by d3f3nder** [comment]
ah i am sorry, i finally found a nice article on how to get this working.

**Comment by f-bader** [comment]
For anybody else looking for guidance
* [Deploy the ARM template using the Azure portal](https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/quickstart-create-templates-use-the-portal)
* You must provide the name of your Sentinel workspace
* If the Sentinel workspace is in a different resource group, specify the name of the Sentinel resource group as well
* Do not deploy in another subscription, the arm template can't handle it
